release-docker-image/action.yaml
semantic-release/action.yaml

Tested here: 
https://github.com/neohelden/actions-test-project/runs/4135466632?check_suite_focus=true

feat: add version prefix to image tag and github tag

---

build-docker-image/action.yaml

New default tested: https://github.com/neohelden/argocd-action/actions/runs/1516461841

feat(build-docker-image): disable maximizing build space per default

---

.github/dependabot.yaml
.github/workflows/build-and-deploy-container-image.yaml
.github/workflows/check-code-compliance.yaml
.github/workflows/delete-pr-deployment.yaml
.github/workflows/release-docker-image.yaml
README.md
build-docker-image/action.yaml

* combines composite actions to reusable workflows for yarn based repositories creating a docker image
* introduce https://github.com/rhysd/actionlint for linting reusable workflow yaml files
* allows deploying PRs to a k8s cluster using ArgoCD
Tested here: https://github.com/neohelden/neo-sentinel-pdf-converter/pull/52

feat: introduce reusable workflows

---

.github/workflows/gitops-create-pr-deployment.yaml
.github/workflows/gitops-delete-pr-deployment.yaml
README.md

Added two reusable workflows for deploying and deleting PRs within gitops repositories. 
Tested here: https://github.com/neohelden/gitops-shared-dev-neap/pull/14

feat: gitops scripts for pr deployment and deletion

---

.github/workflows/build-and-deploy-container-image.yaml
.github/workflows/gitops-create-pr-deployment.yaml
kustomize-check/action.yaml
kustomize-diff/action.yaml

Tested here: https://github.com/neohelden/NEAP/pull/369

feat(build-and-deploy-container-image): start NATS for testing

---

kustomize-diff/action.yaml

Tested: https://github.com/neohelden/gitops-base-neap/runs/4456158952?check_suite_focus=true

fix(kustomize-diff): new, moved and deleted kustomization.yaml cannot be diffed

---

.github/workflows/build-and-deploy-container-image.yaml
.github/workflows/gitops-create-pr-deployment.yaml

Tested: https://github.com/neohelden/actions-test-project/pull/52

feat: add status to link to app

---

.github/workflows/build-and-deploy-container-image.yaml
.github/workflows/release-docker-image.yaml
create-gitops-pr/action.yaml

feat(build-and-deploy-container-image): create PR in gitops repo

---

build-and-test-with-yarn/action.yaml

Tested with keycloak: https://github.com/neohelden/keycloak/actions/runs/1578138501

feat: build docker image only

---

.github/workflows/build-and-deploy-container-image.yaml
.github/workflows/delete-pr-deployment.yaml
argocd-add-status-badge/action.yaml

Tested
* [Deploy](https://github.com/neohelden/keycloak/actions/runs/1581790522)
* [Undeploy](https://github.com/neohelden/keycloak/actions/runs/1581835643)

fix(argocd-add-status-badge): empty pr description contains 'null'

---

.github/workflows/build-and-deploy-container-image.yaml
build-docker-image/action.yaml

Tested here: https://github.com/neohelden/actions-test-project/runs/4548623058?check_suite_focus=true

feat: add additional image tag '<branch-name>-<short-sha>'

---

argocd-remove-status-badge/action.yaml

Fixes an issue where the action deleted a whole PR body

fix: do not delete body when PR does not contain line

---

.github/workflows/build-and-deploy-container-image.yaml

Tested
* [add label on closed pr](https://github.com/neohelden/actions-test-project/actions/runs/1606568701)
* [add label on open pr](https://github.com/neohelden/actions-test-project/actions/runs/1606559990)
* [push to open pr](https://github.com/neohelden/actions-test-project/runs/4594195236)

fix: workflow runs on closed prs

---

.github/workflows/release-docker-image.yaml

With this PR each release will be posted on https://www.notion.so/neohelden/NEAP-Release-Notes-fa31a404f7eb4d619382ca89961e8973
Tested here: https://github.com/neohelden/actions-test-project/actions/runs/1652945137

feat(release-docker-image): publish release notes to Notion.com

---

.github/workflows/build-and-deploy-container-image.yaml

fixes an issue where megalint would not create commit statuses

fix: add status permission for commit status checks

---

.github/workflows/build-and-deploy-container-image.yaml

This adds the branch from where develop originates from to the passbale arguments

feat(build-and-deploy-container-image): add main-branch property to arguments

---

check-code-compliance/action.yaml

Fixes an error where license checks would be run when no package.json file has been defined.

fix(check-code-compliance): do not run licenses

---

build-docker-image/action.yaml

This fixes an error where a scheduled event would not produce a docker image
https://github.com/neohelden/NEAP/runs/6344296477

fix(build-docker-image): add minning branch build

---

.github/workflows/build-and-deploy-container-image.yaml
build-and-test-with-gradle/action.yaml
build-jib-image/action.yaml

Tested here
* [gradle (jib)](https://github.com/neohelden/neap-portal-service/pull/1)
* [yarn (docker)](https://github.com/neohelden/actions-test-project/pull/143)
NEAP-592

feat: enable building jib containers

---

.github/workflows/gitops-base-check.yaml

https://github.com/neohelden/gitops-base-website/runs/6712180983
[NEAP-619](https://neohelden.atlassian.net/browse/NEAP-619)

feat: add reusable workflow for gitops-base repos

---

.github/workflows/build-and-deploy-container-image.yaml
semantic-release/action.yaml

https://github.com/neohelden/actions-test-project/runs/7433893690

fix(semantic-release): install ruby version 2.7

---

build-and-test-with-gradle/action.yaml
check-code-compliance/action.yaml

fix(build-and-test-with-gradle): add all tests results to processed files

---

.github/workflows/build-and-deploy-container-image.yaml
build-docker-image/action.yaml

This adds the ability to clone org-wide submodules

feat(build-docker-image): add submodule cloning

---

.github/workflows/build-and-deploy-container-image.yaml
build-and-test-with-yarn/action.yaml
check-code-compliance/action.yaml
semantic-release/action.yaml

This adds the ability to support Yarn V2 projects in the pipeline

feat: add ability to support yarn berry projects

---

.github/workflows/build-and-deploy-container-image.yaml
build-and-test-with-yarn/action.yaml

This fixes an issue where ESLint v5 would not be run

fix(build-and-test-with-yarn): change arguments ordering
